name = "james"
main = "worker.js"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "data"
database_name = "jamestui"
database_id = "ad917c15-a1d6-4eb0-a3a6-52c8ba2fd33d"

[[r2_buckets]]
binding = "images"
bucket_name = "jamestui"
